package com.hiring.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AiTutorResponse {
    private String response;
    private boolean isMock; // indicates whether it was generated by mock fallback
}
